# Imports

In [1]:
import warnings
warnings.filterwarnings("ignore")

from dask.distributed import Client, progress

client = Client(n_workers=4, threads_per_worker=2, memory_limit="2GB")
client

<Client: 'tcp://127.0.0.1:62395' processes=4 threads=8, memory=8.00 GB>

In [2]:
# import dask arrays
import dask.array as da
import numpy as np

# Assignment

In [3]:
%%time

# creates random dask array 10,000 x 10,000
x = da.random.random((10000, 10000), chunks=(1000, 1000))

# adds the array to its transpose
y = x + x.T

# filters the array and calculates the mean
z = y[::2, 5000:].mean(axis=1)

# evaluates the results
z.compute()

Wall time: 1.12 s


array([0.996808  , 0.99656965, 1.0002325 , ..., 0.99885535, 0.99922672,
       1.00597665])

1. Change the code above by setting chunks=(250, 250). How long does it take to run?

In [4]:
%%time

# creates random dask array 10,000 x 10,000
x = da.random.random((10000, 10000), chunks=(250, 250))

# adds the array to its transpose
y = x + x.T

# filters the array and calculates the mean
z = y[::2, 5000:].mean(axis=1)

# evaluates the results
z.compute()

Wall time: 2.61 s


array([0.99660157, 1.00167499, 1.00977727, ..., 0.99536136, 0.99990718,
       1.00070306])

2. Now, set the parameter to chunks=(500, 500). How long does it take to run? Does this one or the previous one run more quickly? Why?

In [5]:
%%time

# creates random dask array 10,000 x 10,000
x = da.random.random((10000, 10000), chunks=(500, 500))

# adds the array to its transpose
y = x + x.T

# filters the array and calculates the mean
z = y[::2, 5000:].mean(axis=1)

# evaluates the results
z.compute()

Wall time: 975 ms


array([1.00485287, 1.00650599, 0.9948844 , ..., 1.01252427, 1.00415586,
       1.01244356])